### PR TITLE
Added implementation of video upload session, for use with javascript library

### PR DESCRIPTION
**Pull request by drei01**
See http://www.pandastream.com/docs/api#videos_post_videos_upload_json

### CODE REVIEW

**Comment by maxhille** [comment]
Would it be possible to keep JUnit out of the default dependency scope?

Also, could you bump the version number to 0.2.0?

**Comment by drei01** [comment]
Sure, just pushed those changes

**Comment by maxhille** [comment]
Thanks for your work!

**Comment by drei01** [comment]
No problem, glad to be able to contribute.

**Pull request merged**
